# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=150)),
                ('chapter_number', models.IntegerField()),
                ('chapter_content', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_edited', models.DateTimeField(auto_now=True)),
                ('chapter_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=100)),
                ('story_description', models.TextField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('story_image', models.ImageField(blank=True, height_field='height_field', upload_to=story.models.upload_story_image, width_field='width_field')),
                ('story_slug', models.SlugField(unique=True)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story'),
        ),
    ]
